trim whitespace padding from item barcodes (#320)
Submitting an item barcode with leading or trailing whitespace to the
endpoint `circulation/check-out-by-barcode` causes it to fail with a 500
and the response, "Failed to contact storage module:
java.io.IOException: Connection reset by peer".

Fixes UICHKOUT-506